apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-cert
  namespace: wisecow
spec:
  secretName: wisecow-tls
  dnsNames:
    - wisecow.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
